# Armedis Configuration
config:
  redis:
    seed:
      host: 192.168.56.105
      port: 17001
#      password: foobar   # optional

spring:
  application:
    name: armedis
  data:
    redis:
      host: ${config.redis.seed.host}  # Armedis가 seed 기반으로 해석해서 사용
      port: ${config.redis.seed.port}  # Armedis가 seed 기반으로 해석해서 사용
      password: ${config.redis.seed.password:}   # optional
      connect-timeout: 2s            # connectionTimeout
      timeout: 60s                   # commandTimeout (operations)
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
          time-between-eviction-runs: 60s

server:
  service:
    port: 8080
    instanceCount: 1
  config:
    stat:
      enabled: true
      addContentSection: false
      logging:
        enabled: false
    service:
      access:
        logging:
          enabled: false
      http:
        logging:
          enabled: false
  management:
    loginId: admin
    loginPassword: armedis1234!

# Spring Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  cloudfoundry:
    skip-ssl-validation: true