spring:
  application:
    name: armedis-test
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
          time-between-eviction-runs: 60s

config:
  redis:
    seed:
      host: 192.168.56.105
      port: 17001
      password:  # optional

server:
  service:
    port: 8081
    instanceCount: 1
  config:
    stat:
      enabled: false
      addContentSection: false
      logging:
        enableed: false
  management:
    loginId: admin
    loginPassword: armedis1234!

logging:
  level:
    root: INFO
    com.github.armedis: DEBUG
    org.springframework.data.redis: DEBUG